name: Test Library PR

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
    branches: [main]

jobs:
  image_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Project Dependencies
        run: poetry install

      - name: Test PR
        run: |
          source .venv/bin/activate
          pytest
